[package]
name = "sudoku-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
tokio = "1.17.0"
num_cpus = "1.13.1"
cursive = "*"